/**
 * Pure builders that turn the SceneDescription (from core/to3d.ts) into
 * Three.js Object3Ds.
 *
 * Wall geometry strategy
 *   We build each wall as a 2D `THREE.Shape` in the WALL FACE plane (the
 *   "u-v" plane where u runs along the wall and v is height), with one
 *   `THREE.Path` hole per opening. Then we ExtrudeGeometry along the
 *   thickness direction. This gives us REAL holes in the wall geometry
 *   without needing CSG — Three's tessellator handles it natively.
 *
 *   The extruded mesh is then rotated/translated so its u-axis aligns with
 *   the wall direction in the floor plane and its v-axis points up. The
 *   contentRoot in SceneManager handles the final domain-Z-up → scene-Y-up
 *   conversion.
 *
 * Door / window dressing
 *   - Door: a thin rectangular leaf attached to the hinge side, plus a
 *     dark frame around the opening for visual contrast.
 *   - Window: a tinted transparent pane in the middle of the opening, plus
 *     a frame.
 *
 * Materials are cached so disposal stays sane.
 */

import * as THREE from 'three';
import {
  MM_TO_THREE,
  type FloorPolygon,
  type SceneDescription,
  type WallFootprint,
} from '../../../core/to3d';

// ── Materials (cached) ──────────────────────────────────────────────────────

let wallMaterial: THREE.MeshStandardMaterial | null = null;
let wallSelectedMaterial: THREE.MeshStandardMaterial | null = null;
let floorMaterial: THREE.MeshStandardMaterial | null = null;
let frameMaterial: THREE.MeshStandardMaterial | null = null;
let doorLeafMaterial: THREE.MeshStandardMaterial | null = null;
let glassMaterial: THREE.MeshPhysicalMaterial | null = null;

export function getWallMaterial(): THREE.MeshStandardMaterial {
  if (!wallMaterial) {
    wallMaterial = new THREE.MeshStandardMaterial({
      color: 0xf1f5f9,
      roughness: 0.85,
      metalness: 0.0,
      side: THREE.DoubleSide,
    });
  }
  return wallMaterial;
}

export function getSelectedWallMaterial(): THREE.MeshStandardMaterial {
  if (!wallSelectedMaterial) {
    wallSelectedMaterial = new THREE.MeshStandardMaterial({
      color: 0xdbeafe,
      roughness: 0.7,
      metalness: 0.0,
      emissive: 0x1d4ed8,
      emissiveIntensity: 0.05,
      side: THREE.DoubleSide,
    });
  }
  return wallSelectedMaterial;
}

export function getFloorMaterial(): THREE.MeshStandardMaterial {
  if (!floorMaterial) {
    floorMaterial = new THREE.MeshStandardMaterial({
      color: 0xe2e8f0,
      roughness: 0.95,
      metalness: 0.0,
    });
  }
  return floorMaterial;
}

function getFrameMaterial(): THREE.MeshStandardMaterial {
  if (!frameMaterial) {
    frameMaterial = new THREE.MeshStandardMaterial({
      color: 0x334155,
      roughness: 0.6,
      metalness: 0.1,
    });
  }
  return frameMaterial;
}

function getDoorLeafMaterial(): THREE.MeshStandardMaterial {
  if (!doorLeafMaterial) {
    doorLeafMaterial = new THREE.MeshStandardMaterial({
      color: 0x8b5e34,
      roughness: 0.55,
      metalness: 0.05,
    });
  }
  return doorLeafMaterial;
}

function getGlassMaterial(): THREE.MeshPhysicalMaterial {
  if (!glassMaterial) {
    glassMaterial = new THREE.MeshPhysicalMaterial({
      color: 0xbfdbfe,
      roughness: 0.05,
      metalness: 0.0,
      transmission: 0.85,
      thickness: 0.02,
      transparent: true,
      opacity: 0.4,
      ior: 1.45,
      side: THREE.DoubleSide,
    });
  }
  return glassMaterial;
}

// ── Wall builder ────────────────────────────────────────────────────────────

/**
 * Build a single wall mesh with real holes for each opening. Returns a
 * Group containing the wall body + frame + door leaves + window panes,
 * already positioned in domain-mm space (mm → m via MM_TO_THREE).
 *
 * Local axis convention (before basis rotation):
 *   x = u  along wall (a → b)
 *   y = v  height (0 .. wall.height)
 *   z      thickness (0 .. wall.thickness)
 *
 * After the basis rotation we apply:
 *   local x → world wall direction (in floor plane)
 *   local y → world up (z in domain space; SceneManager rotates to scene Y)
 *   local z → world wall left-hand normal (in floor plane)
 *
 * Then we translate by -thickness/2 along the world normal so the wall's
 * geometric centerline matches the floor footprint generated by to3d.ts.
 */
export function buildWallMesh(footprint: WallFootprint): THREE.Group {
  const group = new THREE.Group();
  group.name = `wall:${footprint.wallId}`;
  group.userData = { wallId: footprint.wallId, kind: 'wall' };

  const lengthM = footprint.lengthMm * MM_TO_THREE;
  const heightM = footprint.heightMm * MM_TO_THREE;
  const thicknessM = footprint.thicknessMm * MM_TO_THREE;

  // ── Build face shape with holes ─────────────────────────────────────
  const shape = new THREE.Shape();
  shape.moveTo(0, 0);
  shape.lineTo(lengthM, 0);
  shape.lineTo(lengthM, heightM);
  shape.lineTo(0, heightM);
  shape.closePath();

  for (const h of footprint.holes) {
    const u0 = h.uMin * MM_TO_THREE;
    const u1 = h.uMax * MM_TO_THREE;
    const v0 = h.vMin * MM_TO_THREE;
    const v1 = h.vMax * MM_TO_THREE;
    const path = new THREE.Path();
    path.moveTo(u0, v0);
    path.lineTo(u1, v0);
    path.lineTo(u1, v1);
    path.lineTo(u0, v1);
    path.closePath();
    shape.holes.push(path);
  }

  const geom = new THREE.ExtrudeGeometry(shape, {
    depth: thicknessM,
    bevelEnabled: false,
    curveSegments: 1,
  });

  const wallMesh = new THREE.Mesh(geom, getWallMaterial());
  wallMesh.castShadow = true;
  wallMesh.receiveShadow = true;
  wallMesh.userData = { wallId: footprint.wallId, kind: 'wall' };
  group.add(wallMesh);

  // ── Frame + door leaf / window pane per hole ────────────────────────
  for (const h of footprint.holes) {
    const u0 = h.uMin * MM_TO_THREE;
    const u1 = h.uMax * MM_TO_THREE;
    const v0 = h.vMin * MM_TO_THREE;
    const v1 = h.vMax * MM_TO_THREE;
    const wM = u1 - u0;
    const hM = v1 - v0;
    const cu = (u0 + u1) / 2;
    const cv = (v0 + v1) / 2;

    // Frame: 4 thin boxes around the opening, 30 mm wide, depth = wall thickness + 2 mm
    const frameW = 0.03; // 30 mm
    const frameDepth = thicknessM + 0.002;

    const top = new THREE.Mesh(
      new THREE.BoxGeometry(wM + 2 * frameW, frameW, frameDepth),
      getFrameMaterial(),
    );
    top.position.set(cu, v1 + frameW / 2, thicknessM / 2);
    group.add(top);

    const bottom = new THREE.Mesh(
      new THREE.BoxGeometry(wM + 2 * frameW, frameW, frameDepth),
      getFrameMaterial(),
    );
    bottom.position.set(cu, v0 - frameW / 2, thicknessM / 2);
    group.add(bottom);

    const left = new THREE.Mesh(
      new THREE.BoxGeometry(frameW, hM, frameDepth),
      getFrameMaterial(),
    );
    left.position.set(u0 - frameW / 2, cv, thicknessM / 2);
    group.add(left);

    const right = new THREE.Mesh(
      new THREE.BoxGeometry(frameW, hM, frameDepth),
      getFrameMaterial(),
    );
    right.position.set(u1 + frameW / 2, cv, thicknessM / 2);
    group.add(right);

    if (h.kind === 'window') {
      // Glass pane in the middle of the wall thickness
      const pane = new THREE.Mesh(
        new THREE.BoxGeometry(wM, hM, 0.01),
        getGlassMaterial(),
      );
      pane.position.set(cu, cv, thicknessM / 2);
      pane.userData = { openingId: h.openingId, kind: 'window' };
      group.add(pane);
    } else if (h.kind === 'door') {
      // Door leaf: thin slab attached to the LEFT side (hinge), opens 90° inward.
      const leafThickness = 0.04;
      const leaf = new THREE.Mesh(
        new THREE.BoxGeometry(wM, hM, leafThickness),
        getDoorLeafMaterial(),
      );
      // Position leaf so its hinge edge sits at the LEFT jamb (u = u0).
      // We'll move pivot to that edge by translating geometry, then rotate.
      leaf.geometry.translate(wM / 2, 0, 0);
      leaf.position.set(u0, cv, thicknessM / 2 - leafThickness / 2);
      // Rotate slightly open so it reads as a door (15° inward).
      leaf.rotation.y = -Math.PI / 12;
      leaf.userData = { openingId: h.openingId, kind: 'door' };
      leaf.castShadow = true;
      group.add(leaf);
    }
    // pass-through: no leaf, no glass — just the frame.
  }

  // ── Orient + place the whole group ──────────────────────────────────
  const ax = footprint.aMm.x * MM_TO_THREE;
  const ay = footprint.aMm.y * MM_TO_THREE;
  const dxm = (footprint.bMm.x - footprint.aMm.x) * MM_TO_THREE;
  const dym = (footprint.bMm.y - footprint.aMm.y) * MM_TO_THREE;
  const angle = Math.atan2(dym, dxm); // wall direction in floor plane

  // Build a basis whose:
  //   xAxis = (cos a, sin a, 0)             along wall in floor (domain XY)
  //   yAxis = (0, 0, 1)                     up in domain
  //   zAxis = (-sin a, cos a, 0)            left-hand normal in floor
  const xAxis = new THREE.Vector3(Math.cos(angle), Math.sin(angle), 0);
  const yAxis = new THREE.Vector3(0, 0, 1);
  const zAxis = new THREE.Vector3(-Math.sin(angle), Math.cos(angle), 0);
  const basis = new THREE.Matrix4().makeBasis(xAxis, yAxis, zAxis);

  // Place at wall.a, then offset by -thickness/2 along the normal so the
  // extruded "thickness" range (0..thicknessM) is centered on the centerline.
  const halfT = thicknessM / 2;
  const px = ax - zAxis.x * halfT;
  const py = ay - zAxis.y * halfT;
  const pz = footprint.baseZMm * MM_TO_THREE;
  basis.setPosition(new THREE.Vector3(px, py, pz));

  group.matrixAutoUpdate = false;
  group.matrix.copy(basis);
  group.updateMatrixWorld(true);

  return group;
}

// ── Floor builder ───────────────────────────────────────────────────────────

export function buildFloorMesh(floor: FloorPolygon): THREE.Mesh | null {
  if (floor.points.length < 3) return null;

  const shape = new THREE.Shape();
  const p0 = floor.points[0];
  shape.moveTo(p0.x * MM_TO_THREE, p0.y * MM_TO_THREE);
  for (let i = 1; i < floor.points.length; i++) {
    const p = floor.points[i];
    shape.lineTo(p.x * MM_TO_THREE, p.y * MM_TO_THREE);
  }
  shape.closePath();

  const geometry = new THREE.ShapeGeometry(shape);
  geometry.translate(0, 0, floor.zMm * MM_TO_THREE);
  const mesh = new THREE.Mesh(geometry, getFloorMaterial());
  mesh.receiveShadow = true;
  mesh.name = `floor:${floor.roomId}`;
  mesh.userData = { roomId: floor.roomId, kind: 'floor' };
  return mesh;
}

// ── Equipment placeholder (replaced by GLBs in Phase 6) ─────────────────────

export function buildEquipmentPlaceholder(
  equipmentId: string,
  position: { x: number; y: number; z: number },
  footprint: { width: number; depth: number },
  heightMm: number,
  rotationRad: number,
): THREE.Mesh {
  const w = footprint.width * MM_TO_THREE;
  const d = footprint.depth * MM_TO_THREE;
  const h = heightMm * MM_TO_THREE;
  const geometry = new THREE.BoxGeometry(w, d, h);
  const material = new THREE.MeshStandardMaterial({
    color: 0xcbd5e1,
    roughness: 0.6,
    metalness: 0.2,
  });
  const mesh = new THREE.Mesh(geometry, material);
  mesh.position.set(
    position.x * MM_TO_THREE + w / 2,
    position.y * MM_TO_THREE + d / 2,
    position.z * MM_TO_THREE + h / 2,
  );
  mesh.rotation.z = rotationRad;
  mesh.castShadow = true;
  mesh.receiveShadow = true;
  mesh.userData = { equipmentId, kind: 'equipment' };
  return mesh;
}

// ── Whole-scene builder ────────────────────────────────────────────────────

export interface BuiltScene {
  group: THREE.Group;
  meshByWallId: Map<string, THREE.Object3D>;
  meshByFloorId: Map<string, THREE.Mesh>;
  meshByEquipmentId: Map<string, THREE.Mesh>;
  boundsM: THREE.Box3;
}

/**
 * Build ONLY walls + floor (the "static" scene). Equipment is built and
 * lifecycled separately by Editor3D so GLBs survive store rebuilds and
 * placeholders aren't constantly recreated.
 */
export function buildStaticScene(desc: SceneDescription): BuiltScene {
  const group = new THREE.Group();
  group.name = 'project-static';

  const meshByWallId = new Map<string, THREE.Object3D>();
  const meshByFloorId = new Map<string, THREE.Mesh>();
  const meshByEquipmentId = new Map<string, THREE.Mesh>();

  for (const f of desc.floors) {
    const m = buildFloorMesh(f);
    if (m) {
      group.add(m);
      meshByFloorId.set(f.roomId, m);
    }
  }
  for (const w of desc.walls) {
    const obj = buildWallMesh(w);
    group.add(obj);
    meshByWallId.set(w.wallId, obj);
  }

  // Bounds + return below…
  return finalizeBuiltScene(group, meshByWallId, meshByFloorId, meshByEquipmentId, desc);
}

/** Legacy alias — full scene (walls + floor + placeholder equipment). */
export function buildSceneFromDescription(desc: SceneDescription): BuiltScene {
  const built = buildStaticScene(desc);
  for (const e of desc.equipment) {
    const m = buildEquipmentPlaceholder(
      e.equipmentId,
      e.position,
      e.footprint,
      e.heightMm,
      e.rotationRad,
    );
    built.group.add(m);
    built.meshByEquipmentId.set(e.equipmentId, m);
  }
  return built;
}

function finalizeBuiltScene(
  group: THREE.Group,
  meshByWallId: Map<string, THREE.Object3D>,
  meshByFloorId: Map<string, THREE.Mesh>,
  meshByEquipmentId: Map<string, THREE.Mesh>,
  desc: SceneDescription,
): BuiltScene {

  const boundsM = new THREE.Box3();
  if (desc.bounds) {
    boundsM.setFromCenterAndSize(
      new THREE.Vector3(
        ((desc.bounds.min.x + desc.bounds.max.x) / 2) * MM_TO_THREE,
        ((desc.bounds.min.y + desc.bounds.max.y) / 2) * MM_TO_THREE,
        1.5,
      ),
      new THREE.Vector3(
        Math.max(0.5, (desc.bounds.max.x - desc.bounds.min.x) * MM_TO_THREE),
        Math.max(0.5, (desc.bounds.max.y - desc.bounds.min.y) * MM_TO_THREE),
        3,
      ),
    );
  }

  return { group, meshByWallId, meshByFloorId, meshByEquipmentId, boundsM };
}
