import React, { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { ChevronDown, CheckCircle2, AlertCircle } from 'lucide-react';

export default function CookiePolicyPage() {
  const { t, i18n } = useTranslation();
  const [expandedSections, setExpandedSections] = useState<string[]>([]);
  const toggleSection = (id: string) => {
    setExpandedSections((prev) => prev.includes(id) ? prev.filter((s) => s !== id) : [...prev, id]);
  };
  const isGerman = i18n.language === 'de';
  const sections = [
    {id:'overview', title: isGerman ? 'Was sind Cookies?' : 'What are Cookies?', content: isGerman ? <div className="space-y-2 text-sm text-on-surface-variant"><p>Cookies sind kleine Textdateien, die auf Ihrem Gerät gespeichert werden.</p><p>Diese Richtlinie erklärt, welche Cookies wir verwenden und wie Sie diese verwalten.</p></div> : <div className="space-y-2 text-sm text-on-surface-variant"><p>Cookies are small text files stored on your device.</p><p>This policy explains which cookies we use and how you can manage them.</p></div>},
    {id:'necessary', title: isGerman ? 'Notwendige Cookies (erforderlich)' : 'Necessary Cookies (required)', content: isGerman ? <div className="space-y-2 text-sm text-on-surface-variant"><p className="flex items-start gap-2"><CheckCircle2 size={16} className="text-green-600" />Diese sind <strong>immer aktiviert</strong>.</p><ul className="list-disc list-inside ml-4"><li><strong>Session ID (_sessionid):</strong> 24 Stunden</li><li><strong>CSRF Token (_csrf):</strong> Sitzungsdauer</li><li><strong>Sprachpräferenz (lang):</strong> 1 Jahr</li></ul></div> : <div className="space-y-2 text-sm text-on-surface-variant"><p className="flex items-start gap-2"><CheckCircle2 size={16} className="text-green-600" />These are <strong>always active</strong>.</p><ul className="list-disc list-inside ml-4"><li><strong>Session ID (_sessionid):</strong> 24 hours</li><li><strong>CSRF Token (_csrf):</strong> Session duration</li><li><strong>Language Preference (lang):</strong> 1 year</li></ul></div>},
    {id:'analytics', title: isGerman ? 'Analyse-Cookies (optional)' : 'Analytics Cookies (optional)', content: isGerman ? <div className="space-y-2 text-sm text-on-surface-variant"><p className="flex items-start gap-2"><AlertCircle size={16} className="text-yellow-600" />Mit Ihrer Einwilligung aktivierbar.</p><ul className="list-disc list-inside ml-4"><li><strong>Google Analytics:</strong> 2 Jahre</li><li><strong>Matomo:</strong> 13 Monate</li></ul></div> : <div className="space-y-2 text-sm text-on-surface-variant"><p className="flex items-start gap-2"><AlertCircle size={16} className="text-yellow-600" />Can be enabled with your consent.</p><ul className="list-disc list-inside ml-4"><li><strong>Google Analytics:</strong> 2 years</li><li><strong>Matomo:</strong> 13 months</li></ul></div>},
  ];
  return (
    <div className="min-h-screen bg-surface"><div className="max-w-4xl mx-auto px-4 md:px-8 py-12 md:py-20"><div className="mb-12"><h1 className="text-4xl md:text-5xl font-black text-on-surface font-headline mb-4">{isGerman ? 'Cookie-Richtlinie' : i18n.language === 'en' ? 'Cookie Policy' : 'Çerez Politikası'}</h1></div><div className="space-y-4">{sections.map((section) => (<div key={section.id} className="border border-outline-variant/30 rounded-lg overflow-hidden"><button onClick={() => toggleSection(section.id)} className="w-full flex items-center justify-between px-6 py-4 hover:bg-surface-container-low transition-colors"><h2 className="text-lg font-bold text-on-surface text-left">{section.title}</h2><ChevronDown size={20} className={`text-on-surface-variant transition-transform ${expandedSections.includes(section.id) ? 'rotate-180' : ''}`} /></button>{expandedSections.includes(section.id) && (<div className="px-6 py-4 border-t border-outline-variant/20 bg-surface-container-low">{section.content}</div>)}</div>))}</div><button onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })} className="mt-12 inline-flex items-center gap-2 text-sm font-bold text-primary hover:opacity-70 transition-opacity">↑ {isGerman ? 'Nach oben' : 'Back to top'}</button></div></div>
  );
}
