import React, { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { ChevronDown } from 'lucide-react';

export default function DatenschutzPage() {
  const { t, i18n } = useTranslation();
  const [expandedSections, setExpandedSections] = useState<string[]>([]);
  const toggleSection = (id: string) => {
    setExpandedSections((prev) => prev.includes(id) ? prev.filter((s) => s !== id) : [...prev, id]);
  };
  const isGerman = i18n.language === 'de';
  const sections = [
    {id:'overview', title: isGerman ? 'Überblick und Verantwortliche' : 'Overview and Responsible Party', content: isGerman ? <div className="space-y-2 text-sm text-on-surface-variant"><p><strong>Verantwortlicher:</strong> 2MC Gastro GmbH, [Straße], Deutschland, info@2mcgastro.com</p><p><strong>Datenschutzbeauftragter:</strong> [Name], dpo@2mcgastro.com</p><p>Diese Richtlinie erklärt, wie wir Ihre Daten gemäß DSGVO verarbeiten.</p></div> : i18n.language === 'en' ? <div className="space-y-2 text-sm text-on-surface-variant"><p><strong>Responsible:</strong> 2MC Gastro GmbH, [Street], Germany, info@2mcgastro.com</p><p><strong>Data Protection Officer:</strong> [Name], dpo@2mcgastro.com</p><p>This policy explains how we process your data in accordance with GDPR.</p></div> : <div className="space-y-2 text-sm text-on-surface-variant"><p><strong>Sorumlu:</strong> 2MC Gastro GmbH, [Cadde], Almanya, info@2mcgastro.com</p><p><strong>Veri Koruma Görevlisi:</strong> [Ad], dpo@2mcgastro.com</p><p>Bu politika verilerinizi GDPR'a uygun olarak nasıl işlediğimizi açıklar.</p></div>
    },
    {id:'collection', title: isGerman ? 'Erfassung und Verarbeitung' : 'Collection and Processing', content: isGerman ? <div className="space-y-2 text-sm text-on-surface-variant"><p><strong>Erfasste Daten:</strong> Kontakt, Zahlungs-, Bestell-, Kommunikations-, technische und Marketing-Daten.</p><p><strong>Rechtsgrundlagen (Art. 6 DSGVO):</strong></p><ul className="list-disc list-inside ml-2"><li>Art. 6(1)(a) – Einwilligung</li><li>Art. 6(1)(b) – Vertragserfüllung</li><li>Art. 6(1)(c) – Rechtliche Verpflichtung</li><li>Art. 6(1)(f) – Berechtigte Interessen</li></ul></div> : i18n.language === 'en' ? <div className="space-y-2 text-sm text-on-surface-variant"><p><strong>Data Collected:</strong> Contact, payment, order, communication, technical, and marketing data.</p><p><strong>Legal Basis (Art. 6 GDPR):</strong></p><ul className="list-disc list-inside ml-2"><li>Art. 6(1)(a) – Consent</li><li>Art. 6(1)(b) – Contract performance</li><li>Art. 6(1)(c) – Legal obligation</li><li>Art. 6(1)(f) – Legitimate interest</li></ul></div> : <div className="space-y-2 text-sm text-on-surface-variant"><p><strong>Toplanan Veriler:</strong> İletişim, ödeme, sipariş, iletişim, teknik ve pazarlama verileri.</p><p><strong>Yasal Dayanak (Mad. 6 GDPR):</strong></p><ul className="list-disc list-inside ml-2"><li>Mad. 6(1)(a) – Rıza</li><li>Mad. 6(1)(b) – Sözleşme performansı</li><li>Mad. 6(1)(c) – Yasal yükümlülük</li><li>Mad. 6(1)(f) – Meşru menfaat</li></ul></div>
    },
    {id:'rights', title: isGerman ? 'Ihre Rechte (Art. 15–21 DSGVO)' : 'Your Rights (Art. 15-21 GDPR)', content: isGerman ? <div className="space-y-2 text-sm text-on-surface-variant"><p><strong>Art. 15:</strong> Auskunftsrecht</p><p><strong>Art. 16:</strong> Berichtigungsrecht</p><p><strong>Art. 17:</strong> Recht auf Löschung</p><p><strong>Art. 18:</strong> Einschränkung der Verarbeitung</p><p><strong>Art. 20:</strong> Datenportabilität</p><p><strong>Art. 21:</strong> Widerspruchsrecht</p><p>Kontakt: info@2mcgastro.com</p></div> : i18n.language === 'en' ? <div className="space-y-2 text-sm text-on-surface-variant"><p><strong>Art. 15:</strong> Right of Access</p><p><strong>Art. 16:</strong> Right to Rectification</p><p><strong>Art. 17:</strong> Right to Erasure</p><p><strong>Art. 18:</strong> Right to Restrict Processing</p><p><strong>Art. 20:</strong> Right to Data Portability</p><p><strong>Art. 21:</strong> Right to Object</p><p>Contact: info@2mcgastro.com</p></div> : <div className="space-y-2 text-sm text-on-surface-variant"><p><strong>Mad. 15:</strong> Erişim Hakkı</p><p><strong>Mad. 16:</strong> Düzeltme Hakkı</p><p><strong>Mad. 17:</strong> Silinme Hakkı</p><p><strong>Mad. 18:</strong> İşleme Kısıtlanması</p><p><strong>Mad. 20:</strong> Veri Taşınabilirliği</p><p><strong>Mad. 21:</strong> İtiraz Hakkı</p><p>İletişim: info@2mcgastro.com</p></div>
    },
    {id:'retention', title: isGerman ? 'Speicherdauer' : 'Retention Period', content: isGerman ? <div className="space-y-2 text-sm text-on-surface-variant"><ul className="list-disc list-inside ml-2"><li><strong>Bestelldaten:</strong> 3 Jahre</li><li><strong>Rechnungsdaten:</strong> 10 Jahre</li><li><strong>Kontaktdaten:</strong> Bis zur Löschung</li><li><strong>Newsletter:</strong> Bis Widerruf</li></ul></div> : i18n.language === 'en' ? <div className="space-y-2 text-sm text-on-surface-variant"><ul className="list-disc list-inside ml-2"><li><strong>Order data:</strong> 3 years</li><li><strong>Invoice data:</strong> 10 years</li><li><strong>Contact data:</strong> Until deletion</li><li><strong>Newsletter:</strong> Until withdrawal</li></ul></div> : <div className="space-y-2 text-sm text-on-surface-variant"><ul className="list-disc list-inside ml-2"><li><strong>Sipariş verileri:</strong> 3 yıl</li><li><strong>Fatura verileri:</strong> 10 yıl</li><li><strong>İletişim verileri:</strong> Silinmesine kadar</li><li><strong>Haber bülteni:</strong> Geri çekmeye kadar</li></ul></div>
    },
  ];
  return (
    <div className="min-h-screen bg-surface"><div className="max-w-4xl mx-auto px-4 md:px-8 py-12 md:py-20"><div className="mb-12"><h1 className="text-4xl md:text-5xl font-black text-on-surface font-headline mb-4">{isGerman ? 'Datenschutz' : i18n.language === 'en' ? 'Privacy Policy' : 'Gizlilik Politikası'}</h1><p className="text-sm text-on-surface-variant">{isGerman ? 'Aktualisiert' : i18n.language === 'en' ? 'Updated' : 'Güncellendi'} {new Date().toLocaleDateString(i18n.language, { year: 'numeric', month: 'long', day: 'numeric' })}</p></div><div className="space-y-4">{sections.map((section) => (<div key={section.id} className="border border-outline-variant/30 rounded-lg overflow-hidden"><button onClick={() => toggleSection(section.id)} className="w-full flex items-center justify-between px-6 py-4 hover:bg-surface-container-low transition-colors"><h2 className="text-lg font-bold text-on-surface text-left">{section.title}</h2><ChevronDown size={20} className={`text-on-surface-variant transition-transform ${expandedSections.includes(section.id) ? 'rotate-180' : ''}`} /></button>{expandedSections.includes(section.id) && (<div className="px-6 py-4 border-t border-outline-variant/20 bg-surface-container-low">{section.content}</div>)}</div>))}</div><button onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })} className="mt-12 inline-flex items-center gap-2 text-sm font-bold text-primary hover:opacity-70 transition-opacity">↑ {isGerman ? 'Nach oben' : i18n.language === 'en' ? 'Back to top' : 'Üste git'}</button></div></div>
  );
}
